function createfigure(XData1, YData1, Y1, YData2)
%CREATEFIGURE(XData1, YData1, Y1, YData2)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  Y1:  vector of stairs y data
%  YDATA2:  line ydata

%  Auto-generated by MATLAB on 01-Sep-2024 00:16:36

% Create figure
figure('Tag','ScopePrintToFigure',...
    'Color',[0.156862745098039 0.156862745098039 0.156862745098039]);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uipanel currently does not support code generation, enter 'doc uipanel' for correct input syntax
% In order to generate code for uipanel, you may use GUIDE. Enter 'doc guide' for more information
% uipanel(...);

% Create axes
axes1 = axes('Tag','DisplayAxes1_RealMag',...
hold(axes1,'on');
colororder([1 0.909803921568627 0.392156862745098;0.149019607843137 0.549019607843137 0.866666666666667;0.96078431372549 0.466666666666667 0.16078431372549;0.286274509803922 0.858823529411765 0.250980392156863;0.752941176470588 0.36078431372549 0.984313725490196;0.423529411764706 0.956862745098039 1;0.949019607843137 0.403921568627451 0.772549019607843]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create line
line(XData1,YData1,'DisplayName','Voltage Measurement3',...
    'Tag','DisplayLine1',...
    'LineWidth',2,...
    'Color',[0 0 1]);

% Create ylabel
ylabel('Vac');

% Create xlabel
xlabel('Time (sec)');

% Create title
title('Controlled Half wave rectifier','FontSize',12);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1.33229217140416 1.5653666666667]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-406.583063136307 406.566212163647]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'ClippingStyle','rectangle','FontSize',8,'GridAlpha',0.4,...
    'GridColor',[0.686274509803922 0.686274509803922 0.686274509803922],...
    'TickLabelInterpreter','none','XColor',[0 0 0],'XGrid','on','XTickLabel','',...
    'YColor',[0 0 0],'YGrid','on','ZColor',[0 0 0]);
% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uipanel currently does not support code generation, enter 'doc uipanel' for correct input syntax
% In order to generate code for uipanel, you may use GUIDE. Enter 'doc guide' for more information
% uipanel(...);

% Create axes
axes2 = axes('Tag','DisplayAxes2_RealMag',...
hold(axes2,'on');
colororder([1 0.909803921568627 0.392156862745098;0.149019607843137 0.549019607843137 0.866666666666667;0.96078431372549 0.466666666666667 0.16078431372549;0.286274509803922 0.858823529411765 0.250980392156863;0.752941176470588 0.36078431372549 0.984313725490196;0.423529411764706 0.956862745098039 1;0.949019607843137 0.403921568627451 0.772549019607843]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create stairs
stairs(XData1,Y1,'DisplayName','Pulse Generator','Tag','DisplayLine1',...
    'LineWidth',2,...
    'Color',[1 0.909803921568627 0.392156862745098]);

% Create xlabel
xlabel('Time (sec)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[1.33229217140416 1.5653666666667]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[-0.125 1.125]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes2,[-1 1]);
box(axes2,'on');
hold(axes2,'off');
% Set the remaining axes properties
set(axes2,'ClippingStyle','rectangle','FontSize',8,'GridAlpha',0.4,...
    'GridColor',[0.686274509803922 0.686274509803922 0.686274509803922],...
    'TickLabelInterpreter','none','XColor',[0 0 0],'XGrid','on','XTickLabel','',...
    'YColor',[0 0 0],'YGrid','on','ZColor',[0 0 0]);
% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uipanel currently does not support code generation, enter 'doc uipanel' for correct input syntax
% In order to generate code for uipanel, you may use GUIDE. Enter 'doc guide' for more information
% uipanel(...);

% Create axes
axes3 = axes('Tag','DisplayAxes3_RealMag');
hold(axes3,'on');
colororder([1 0.909803921568627 0.392156862745098;0.149019607843137 0.549019607843137 0.866666666666667;0.96078431372549 0.466666666666667 0.16078431372549;0.286274509803922 0.858823529411765 0.250980392156863;0.752941176470588 0.36078431372549 0.984313725490196;0.423529411764706 0.956862745098039 1;0.949019607843137 0.403921568627451 0.772549019607843]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create line
line(XData1,YData2,'DisplayName','Voltage Measurement1',...
    'Tag','DisplayLine1',...
    'LineWidth',2,...
    'Color',[1 0 0]);

% Create ylabel
ylabel('Vout (V)');

% Create xlabel
xlabel(' Time (sec)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[1.33229217140416 1.5653666666667]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[-40.8342089265206 365.002515157951]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes3,[-1 1]);
box(axes3,'on');
hold(axes3,'off');
% Set the remaining axes properties
set(axes3,'ClippingStyle','rectangle','FontSize',8,'GridAlpha',0.4,...
    'GridColor',[0.686274509803922 0.686274509803922 0.686274509803922],...
    'TickLabelInterpreter','none','XColor',[0 0 0],'XGrid','on','YColor',...
    [0 0 0],'YGrid','on','ZColor',[0 0 0]);
% Create text
text('Tag','TimeOffsetStatus','Units','pixels','VerticalAlignment','bottom',...
    'FontSize',8,...
    'Position',[0 0 0],...
    'Color',[0.686274509803922 0.686274509803922 0.686274509803922],...
    'Visible','on');
